image: Ubuntu2204
stack: node 20

branches:
  only:
    - master
    - main

cache: node_modules

install:
  - npm install
  - npm install wait-on

build: off

build_script:
  - chmod +x node_modules/.bin/webpack
  - npm run build

test_script:
  - chmod +x node_modules/.bin/jest
  - npm start &
  - npx wait-on http://localhost:9000
  - npm run lint && npm run test -- --passWithNoTests

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"